"""domain schema

Revision ID: b0f6a1fec6f3
Revises: fa9ee5cbfaff
Create Date: 2026-10-05 20:23:11.333090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0f6a1fec6f3"
down_revision: str | Sequence[str] | None = "fa9ee5cbfaff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="record_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index("uq_categories_name_lower", "categories", [sa.literal_column("lower(name)")], unique=True)
    op.create_table(
        "counters",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_counters")),
    )
    op.create_table(
        "jobs",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("location", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("experience_required", sa.String(length=120), nullable=True),
        sa.Column("posted_on", sa.Date(), nullable=False),
        sa.Column("closing_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Enum("OPEN", "CLOSED", name="job_status"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "closing_date IS NULL OR closing_date >= posted_on", name=op.f("ck_jobs_closing_after_post")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_table(
        "program_types",
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="record_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_types")),
    )
    op.create_index(
        "uq_program_types_name_lower", "program_types", [sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "programmes",
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("age_group", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("duration", sa.String(length=80), nullable=True),
        sa.Column("training_days", sa.String(length=80), nullable=True),
        sa.Column("coach_label", sa.String(length=80), nullable=True),
        sa.Column("benefits", sa.ARRAY(sa.String(length=120)), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="record_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programmes")),
        sa.UniqueConstraint("slug", name=op.f("uq_programmes_slug")),
    )
    op.create_table(
        "training_centers",
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("phone", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="record_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_centers")),
    )
    op.create_index(
        "uq_training_centers_name_lower", "training_centers", [sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "enquiries",
        sa.Column("parent_name", sa.String(length=120), nullable=False),
        sa.Column("player_name", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=10), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("programme_id", sa.Uuid(), nullable=True),
        sa.Column("subject", sa.String(length=120), nullable=True),
        sa.Column("message", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.Enum("NEW", "CONTACTED", "RESOLVED", name="enquiry_status"), nullable=False),
        sa.Column("submitter_ip", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["programme_id"],
            ["programmes.id"],
            name=op.f("fk_enquiries_programme_id_programmes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enquiries")),
    )
    op.create_index(op.f("ix_enquiries_programme_id"), "enquiries", ["programme_id"], unique=False)
    op.create_index("ix_enquiries_status_created", "enquiries", ["status", "created_at"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PAYMENT",
                "ADMISSION",
                "FEE_DUE",
                "ENQUIRY",
                "APPLICATION",
                "SYSTEM",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("link", sa.String(length=200), nullable=True),
        sa.Column("related_id", sa.Uuid(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_index("ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False)
    op.create_table(
        "stored_files",
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("visibility", sa.Enum("PUBLIC", "PRIVATE", name="file_visibility"), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "STUDENT_PHOTO",
                "STUDENT_DOCUMENT",
                "COACH_PHOTO",
                "COACH_DOCUMENT",
                "TEAM_PHOTO",
                "GALLERY_IMAGE",
                "GALLERY_THUMBNAIL",
                "PAYMENT_SCREENSHOT",
                "RESUME",
                name="file_purpose",
            ),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_stored_files_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_stored_files_storage_key")),
    )
    op.create_index(
        "ix_stored_files_purpose_created_at", "stored_files", ["purpose", "created_at"], unique=False
    )
    op.create_table(
        "coach_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.String(length=10), nullable=False),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", "OTHER", name="gender"), nullable=True),
        sa.Column(
            "blood_group",
            sa.Enum("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", name="blood_group"),
            nullable=True,
        ),
        sa.Column("experience_years", sa.SmallInteger(), nullable=False),
        sa.Column("joined_date", sa.Date(), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("bio", sa.String(length=1000), nullable=True),
        sa.Column("photo_file_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_file_id"],
            ["stored_files.id"],
            name=op.f("fk_coach_profiles_photo_file_id_stored_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_coach_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coach_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_coach_profiles_user_id")),
    )
    op.create_table(
        "gallery_items",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("caption", sa.String(length=300), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("is_wide", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("image_file_id", sa.Uuid(), nullable=False),
        sa.Column("thumbnail_file_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="record_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["image_file_id"],
            ["stored_files.id"],
            name=op.f("fk_gallery_items_image_file_id_stored_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["thumbnail_file_id"],
            ["stored_files.id"],
            name=op.f("fk_gallery_items_thumbnail_file_id_stored_files"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gallery_items")),
    )
    op.create_index(op.f("ix_gallery_items_category"), "gallery_items", ["category"], unique=False)
    op.create_table(
        "job_applications",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("phone", sa.String(length=10), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("cv_file_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("UNDER_REVIEW", "SHORTLISTED", "REJECTED", name="application_status"),
            nullable=False,
        ),
        sa.Column("submitter_ip", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cv_file_id"],
            ["stored_files.id"],
            name=op.f("fk_job_applications_cv_file_id_stored_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_applications_job_id_jobs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_applications")),
    )
    op.create_index(op.f("ix_job_applications_job_id"), "job_applications", ["job_id"], unique=False)
    op.create_index(
        "ix_job_applications_status_created", "job_applications", ["status", "created_at"], unique=False
    )
    op.create_table(
        "payment_submissions",
        sa.Column("submission_number", sa.String(length=20), nullable=False),
        sa.Column("student_name", sa.String(length=120), nullable=False),
        sa.Column("parent_mobile", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.Enum("UPI", "CASH", name="submission_method"), nullable=False),
        sa.Column("transaction_reference", sa.String(length=80), nullable=True),
        sa.Column("handed_over_to", sa.String(length=120), nullable=True),
        sa.Column("screenshot_file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "VERIFIED", "REJECTED", name="submission_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.String(length=300), nullable=True),
        sa.Column("remarks", sa.String(length=500), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitter_ip", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "payment_method <> 'CASH' OR handed_over_to IS NOT NULL",
            name=op.f("ck_payment_submissions_cash_needs_receiver"),
        ),
        sa.CheckConstraint(
            "payment_method <> 'UPI' OR screenshot_file_id IS NOT NULL",
            name=op.f("ck_payment_submissions_upi_needs_screenshot"),
        ),
        sa.CheckConstraint(
            "status <> 'REJECTED' OR rejection_reason IS NOT NULL",
            name=op.f("ck_payment_submissions_rejection_needs_reason"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payment_submissions_amount_positive")),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_payment_submissions_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["screenshot_file_id"],
            ["stored_files.id"],
            name=op.f("fk_payment_submissions_screenshot_file_id_stored_files"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_submissions")),
        sa.UniqueConstraint("submission_number", name=op.f("uq_payment_submissions_submission_number")),
    )
    op.create_index(
        op.f("ix_payment_submissions_parent_mobile"), "payment_submissions", ["parent_mobile"], unique=False
    )
    op.create_index(
        "ix_payment_submissions_status_created", "payment_submissions", ["status", "created_at"], unique=False
    )
    op.create_table(
        "students",
        sa.Column("student_code", sa.String(length=20), nullable=False),
        sa.Column("admission_number", sa.String(length=30), nullable=False),
        sa.Column("admission_date", sa.Date(), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", "OTHER", name="gender"), nullable=False),
        sa.Column(
            "blood_group",
            sa.Enum("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", name="blood_group"),
            nullable=True,
        ),
        sa.Column("phone", sa.String(length=10), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("photo_file_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("program_type_id", sa.Uuid(), nullable=False),
        sa.Column("training_center_id", sa.Uuid(), nullable=False),
        sa.Column("batch", sa.Enum("MORNING", "EVENING", "WEEKEND", name="batch"), nullable=False),
        sa.Column("monthly_fee", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="record_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("remarks", sa.String(length=500), nullable=True),
        sa.Column("parent_name", sa.String(length=120), nullable=False),
        sa.Column(
            "parent_relationship",
            sa.Enum("FATHER", "MOTHER", "GUARDIAN", "OTHER", name="relationship"),
            nullable=False,
        ),
        sa.Column("parent_phone", sa.String(length=10), nullable=False),
        sa.Column("parent_email", postgresql.CITEXT(), nullable=True),
        sa.Column("parent_address", sa.String(length=300), nullable=True),
        sa.Column("emergency_name", sa.String(length=120), nullable=True),
        sa.Column("emergency_relationship", sa.String(length=40), nullable=True),
        sa.Column("emergency_phone", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("monthly_fee >= 0", name=op.f("ck_students_monthly_fee_non_negative")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_students_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["photo_file_id"],
            ["stored_files.id"],
            name=op.f("fk_students_photo_file_id_stored_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["program_type_id"],
            ["program_types.id"],
            name=op.f("fk_students_program_type_id_program_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["training_center_id"],
            ["training_centers.id"],
            name=op.f("fk_students_training_center_id_training_centers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint("admission_number", name=op.f("uq_students_admission_number")),
        sa.UniqueConstraint("student_code", name=op.f("uq_students_student_code")),
    )
    op.create_index(op.f("ix_students_category_id"), "students", ["category_id"], unique=False)
    op.create_index(op.f("ix_students_date_of_birth"), "students", ["date_of_birth"], unique=False)
    op.create_index(
        "ix_students_full_name_trgm",
        "students",
        ["full_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"full_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_students_parent_name_trgm",
        "students",
        ["parent_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"parent_name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_students_parent_phone"), "students", ["parent_phone"], unique=False)
    op.create_index(op.f("ix_students_program_type_id"), "students", ["program_type_id"], unique=False)
    op.create_index("ix_students_status_category", "students", ["status", "category_id"], unique=False)
    op.create_index(op.f("ix_students_training_center_id"), "students", ["training_center_id"], unique=False)
    op.create_table(
        "team_members",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("designation", sa.String(length=60), nullable=False),
        sa.Column("biography", sa.String(length=500), nullable=True),
        sa.Column("photo_file_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="record_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_file_id"],
            ["stored_files.id"],
            name=op.f("fk_team_members_photo_file_id_stored_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_members")),
    )
    op.create_table(
        "coach_categories",
        sa.Column("coach_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_coach_categories_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coach_profiles.id"],
            name=op.f("fk_coach_categories_coach_id_coach_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("coach_id", "category_id", name=op.f("pk_coach_categories")),
    )
    op.create_index(
        op.f("ix_coach_categories_category_id"), "coach_categories", ["category_id"], unique=False
    )
    op.create_table(
        "coach_documents",
        sa.Column("coach_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("CONTRACT", "GENERAL", name="document_kind"),
            server_default="GENERAL",
            nullable=False,
        ),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coach_profiles.id"],
            name=op.f("fk_coach_documents_coach_id_coach_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["stored_files.id"],
            name=op.f("fk_coach_documents_file_id_stored_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_coach_documents_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coach_documents")),
        sa.UniqueConstraint("file_id", name=op.f("uq_coach_documents_file_id")),
    )
    op.create_index(op.f("ix_coach_documents_coach_id"), "coach_documents", ["coach_id"], unique=False)
    op.create_table(
        "fee_ledger_entries",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("amount_due", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column("discount_reason", sa.String(length=300), nullable=True),
        sa.Column("amount_paid", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("amount_due >= 0", name=op.f("ck_fee_ledger_entries_amount_due_non_negative")),
        sa.CheckConstraint("amount_paid >= 0", name=op.f("ck_fee_ledger_entries_amount_paid_non_negative")),
        sa.CheckConstraint(
            "discount + amount_paid <= amount_due", name=op.f("ck_fee_ledger_entries_not_overpaid")
        ),
        sa.CheckConstraint("discount >= 0", name=op.f("ck_fee_ledger_entries_discount_non_negative")),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_fee_ledger_entries_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_ledger_entries")),
        sa.UniqueConstraint("student_id", "period", name="uq_fee_ledger_entries_student_period"),
    )
    op.create_index(
        "ix_fee_ledger_entries_period_student", "fee_ledger_entries", ["period", "student_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("receipt_number", sa.String(length=30), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "mode", sa.Enum("CASH", "BANK_TRANSFER", "UPI", "CHEQUE", name="payment_mode"), nullable=False
        ),
        sa.Column("paid_on", sa.Date(), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("remarks", sa.String(length=500), nullable=True),
        sa.Column("source", sa.Enum("MANUAL", "SUBMISSION", name="payment_source"), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("VALID", "VOIDED", name="payment_status"),
            server_default="VALID",
            nullable=False,
        ),
        sa.Column("void_reason", sa.String(length=300), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_payments_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_payments_student_id_students"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["payment_submissions.id"],
            name=op.f("fk_payments_submission_id_payment_submissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_id"], ["users.id"], name=op.f("fk_payments_voided_by_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("receipt_number", name=op.f("uq_payments_receipt_number")),
        sa.UniqueConstraint("submission_id", name=op.f("uq_payments_submission_id")),
    )
    op.create_index(op.f("ix_payments_paid_on"), "payments", ["paid_on"], unique=False)
    op.create_index(op.f("ix_payments_student_id"), "payments", ["student_id"], unique=False)
    op.create_table(
        "performance_reports",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("coach_id", sa.Uuid(), nullable=False),
        sa.Column("report_period", sa.String(length=60), nullable=False),
        sa.Column("recorded_date", sa.Date(), nullable=False),
        sa.Column("position", sa.String(length=60), nullable=True),
        sa.Column("strong_foot", sa.Enum("RIGHT", "LEFT", "BOTH", name="strong_foot"), nullable=False),
        sa.Column("strengths", sa.Text(), nullable=False),
        sa.Column("areas_for_improvement", sa.Text(), nullable=False),
        sa.Column("development_goals", sa.ARRAY(sa.String(length=60)), server_default="{}", nullable=False),
        sa.Column("custom_goal", sa.String(length=300), nullable=True),
        sa.Column("coach_remarks", sa.Text(), nullable=False),
        sa.Column("overall_rating", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "overall_rating BETWEEN 1 AND 5", name=op.f("ck_performance_reports_overall_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coach_profiles.id"],
            name=op.f("fk_performance_reports_coach_id_coach_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_performance_reports_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_performance_reports")),
        sa.UniqueConstraint("student_id", "report_period", name="uq_performance_reports_student_period"),
    )
    op.create_index(
        op.f("ix_performance_reports_coach_id"), "performance_reports", ["coach_id"], unique=False
    )
    op.create_index(
        op.f("ix_performance_reports_student_id"), "performance_reports", ["student_id"], unique=False
    )
    op.create_table(
        "student_documents",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["stored_files.id"],
            name=op.f("fk_student_documents_file_id_stored_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_student_documents_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_student_documents_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_documents")),
        sa.UniqueConstraint("file_id", name=op.f("uq_student_documents_file_id")),
    )
    op.create_index(
        op.f("ix_student_documents_student_id"), "student_documents", ["student_id"], unique=False
    )
    op.create_table(
        "training_sessions",
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("created_by_coach_id", sa.Uuid(), nullable=False),
        sa.Column("venue", sa.String(length=200), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("weekly_topic", sa.String(length=200), nullable=True),
        sa.Column("daily_topic", sa.String(length=200), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "end_time IS NULL OR start_time IS NULL OR end_time > start_time",
            name=op.f("ck_training_sessions_time_order"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_coach_id"],
            ["coach_profiles.id"],
            name=op.f("fk_training_sessions_created_by_coach_id_coach_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_sessions")),
    )
    op.create_index(
        op.f("ix_training_sessions_created_by_coach_id"),
        "training_sessions",
        ["created_by_coach_id"],
        unique=False,
    )
    op.create_index(
        "ix_training_sessions_daily_topic_trgm",
        "training_sessions",
        ["daily_topic"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"daily_topic": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_training_sessions_session_date"), "training_sessions", ["session_date"], unique=False
    )
    op.create_table(
        "payment_allocations",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("ledger_entry_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payment_allocations_amount_positive")),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["fee_ledger_entries.id"],
            name=op.f("fk_payment_allocations_ledger_entry_id_fee_ledger_entries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_allocations_payment_id_payments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_allocations")),
        sa.UniqueConstraint("payment_id", "ledger_entry_id", name="uq_payment_allocations_payment_entry"),
    )
    op.create_index(
        op.f("ix_payment_allocations_ledger_entry_id"),
        "payment_allocations",
        ["ledger_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_allocations_payment_id"), "payment_allocations", ["payment_id"], unique=False
    )
    op.create_table(
        "performance_skill_ratings",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column(
            "skill",
            sa.Enum(
                "TECHNICAL_ABILITY",
                "TACTICAL_UNDERSTANDING",
                "BALL_CONTROL_FIRST_TOUCH",
                "PASSING",
                "DRIBBLING",
                "SHOOTING_FINISHING",
                "DEFENDING",
                "DECISION_MAKING",
                "INDIVIDUAL_SKILLS",
                "TEAMWORK",
                "COMMUNICATION",
                "HARD_WORK",
                "DISCIPLINE",
                "CHARACTER_ATTITUDE",
                "FITNESS",
                name="skill",
            ),
            nullable=False,
        ),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_performance_skill_ratings_rating_range")),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["performance_reports.id"],
            name=op.f("fk_performance_skill_ratings_report_id_performance_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("report_id", "skill", name=op.f("pk_performance_skill_ratings")),
    )
    op.create_table(
        "session_categories",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_session_categories_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_session_categories_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", "category_id", name=op.f("pk_session_categories")),
    )
    op.create_index(
        op.f("ix_session_categories_category_id"), "session_categories", ["category_id"], unique=False
    )
    op.create_table(
        "session_coaches",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("coach_id", sa.Uuid(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("role", sa.Enum("CREATOR", "CO_COACH", name="session_coach_role"), nullable=False),
        sa.Column(
            "status", sa.Enum("PRESENT", "ABSENT", "INFORMED", name="attendance_status"), nullable=False
        ),
        sa.Column("remarks", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coach_profiles.id"],
            name=op.f("fk_session_coaches_coach_id_coach_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_session_coaches_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", "coach_id", name=op.f("pk_session_coaches")),
        sa.UniqueConstraint("coach_id", "session_date", name="uq_session_coaches_coach_date"),
    )
    op.create_table(
        "session_splits",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("heading", sa.String(length=120), nullable=False),
        sa.Column("duration_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("explanation", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "duration_minutes BETWEEN 1 AND 300", name=op.f("ck_session_splits_duration_range")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_session_splits_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_splits")),
        sa.UniqueConstraint("session_id", "position", name="uq_session_splits_session_position"),
    )
    op.create_index(op.f("ix_session_splits_session_id"), "session_splits", ["session_id"], unique=False)
    op.create_table(
        "student_attendance",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.Enum("PRESENT", "ABSENT", "INFORMED", name="attendance_status"), nullable=False
        ),
        sa.Column("remarks", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_student_attendance_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_student_attendance_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_attendance")),
        sa.UniqueConstraint("session_id", "student_id", name="uq_student_attendance_session_student"),
    )
    op.create_index(
        "ix_student_attendance_date_status", "student_attendance", ["session_date", "status"], unique=False
    )
    op.create_index(
        "ix_student_attendance_student_date",
        "student_attendance",
        ["student_id", "session_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_student_attendance_student_date", table_name="student_attendance")
    op.drop_index("ix_student_attendance_date_status", table_name="student_attendance")
    op.drop_table("student_attendance")
    op.drop_index(op.f("ix_session_splits_session_id"), table_name="session_splits")
    op.drop_table("session_splits")
    op.drop_table("session_coaches")
    op.drop_index(op.f("ix_session_categories_category_id"), table_name="session_categories")
    op.drop_table("session_categories")
    op.drop_table("performance_skill_ratings")
    op.drop_index(op.f("ix_payment_allocations_payment_id"), table_name="payment_allocations")
    op.drop_index(op.f("ix_payment_allocations_ledger_entry_id"), table_name="payment_allocations")
    op.drop_table("payment_allocations")
    op.drop_index(op.f("ix_training_sessions_session_date"), table_name="training_sessions")
    op.drop_index(
        "ix_training_sessions_daily_topic_trgm",
        table_name="training_sessions",
        postgresql_using="gin",
        postgresql_ops={"daily_topic": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_training_sessions_created_by_coach_id"), table_name="training_sessions")
    op.drop_table("training_sessions")
    op.drop_index(op.f("ix_student_documents_student_id"), table_name="student_documents")
    op.drop_table("student_documents")
    op.drop_index(op.f("ix_performance_reports_student_id"), table_name="performance_reports")
    op.drop_index(op.f("ix_performance_reports_coach_id"), table_name="performance_reports")
    op.drop_table("performance_reports")
    op.drop_index(op.f("ix_payments_student_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_paid_on"), table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_fee_ledger_entries_period_student", table_name="fee_ledger_entries")
    op.drop_table("fee_ledger_entries")
    op.drop_index(op.f("ix_coach_documents_coach_id"), table_name="coach_documents")
    op.drop_table("coach_documents")
    op.drop_index(op.f("ix_coach_categories_category_id"), table_name="coach_categories")
    op.drop_table("coach_categories")
    op.drop_table("team_members")
    op.drop_index(op.f("ix_students_training_center_id"), table_name="students")
    op.drop_index("ix_students_status_category", table_name="students")
    op.drop_index(op.f("ix_students_program_type_id"), table_name="students")
    op.drop_index(op.f("ix_students_parent_phone"), table_name="students")
    op.drop_index(
        "ix_students_parent_name_trgm",
        table_name="students",
        postgresql_using="gin",
        postgresql_ops={"parent_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_students_full_name_trgm",
        table_name="students",
        postgresql_using="gin",
        postgresql_ops={"full_name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_students_date_of_birth"), table_name="students")
    op.drop_index(op.f("ix_students_category_id"), table_name="students")
    op.drop_table("students")
    op.drop_index("ix_payment_submissions_status_created", table_name="payment_submissions")
    op.drop_index(op.f("ix_payment_submissions_parent_mobile"), table_name="payment_submissions")
    op.drop_table("payment_submissions")
    op.drop_index("ix_job_applications_status_created", table_name="job_applications")
    op.drop_index(op.f("ix_job_applications_job_id"), table_name="job_applications")
    op.drop_table("job_applications")
    op.drop_index(op.f("ix_gallery_items_category"), table_name="gallery_items")
    op.drop_table("gallery_items")
    op.drop_table("coach_profiles")
    op.drop_index("ix_stored_files_purpose_created_at", table_name="stored_files")
    op.drop_table("stored_files")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_index(
        "ix_notifications_unread", table_name="notifications", postgresql_where=sa.text("read_at IS NULL")
    )
    op.drop_table("notifications")
    op.drop_index("ix_enquiries_status_created", table_name="enquiries")
    op.drop_index(op.f("ix_enquiries_programme_id"), table_name="enquiries")
    op.drop_table("enquiries")
    op.drop_index("uq_training_centers_name_lower", table_name="training_centers")
    op.drop_table("training_centers")
    op.drop_table("programmes")
    op.drop_index("uq_program_types_name_lower", table_name="program_types")
    op.drop_table("program_types")
    op.drop_table("jobs")
    op.drop_table("counters")
    op.drop_index("uq_categories_name_lower", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
    # Autogenerate does not drop PostgreSQL enum types.
    sa.Enum(name="record_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="gender").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="blood_group").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="batch").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="relationship").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="attendance_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="session_coach_role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="strong_foot").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="skill").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="payment_mode").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="payment_source").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="payment_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="submission_method").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="submission_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="file_visibility").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="file_purpose").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="document_kind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="job_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="application_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="enquiry_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="notification_type").drop(op.get_bind(), checkfirst=True)
