"""unique emails for students and job applications

Revision ID: ed0c51279a9e
Revises: e2d3f4a5b6c7
Create Date: 2026-10-06 01:01:31.170952

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed0c51279a9e'
down_revision: str | Sequence[str] | None = 'e2d3f4a5b6c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_job_applications_job_email', 'job_applications', ['job_id', 'email'])
    op.create_index('uq_students_email', 'students', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_students_email', table_name='students', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_constraint('uq_job_applications_job_email', 'job_applications', type_='unique')
    # ### end Alembic commands ###
